# -*- coding: utf-8 -*-
"""Kaggle_Signlanguage1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zY2c-E_XeNTjLMTtPK1oZZSQk6sAMhaq
"""

import os

# 密钥存入 Linux 系统环境变量中
os.environ['KAGGLE_API_TOKEN'] = "KGAT_504ca0dcbfa6bd4ab8bc4ef4a66f4f17"

# 验证一下是否设置成功
print("环境变量已设置:", os.environ.get('KAGGLE_API_TOKEN')[:10] + "...")

import os

# Kaggle 账号模型连接
os.environ['KAGGLE_USERNAME'] = "yh0831"
os.environ['KAGGLE_KEY'] = "KGAT_504ca0dcbfa6bd4ab8bc4ef4a66f4f17"

# 测试是否连接成功
!pip install -q kaggle
!kaggle competitions list

import sys
import os

print("--- Checking MediaPipe installation ---")

try:
    import mediapipe as mp
    print(f"MediaPipe is installed. Version: {mp.__version__}")
    print(f"MediaPipe installation path: {os.path.dirname(mp.__file__)}")

    # Check if 'solutions' attribute exists directly
    if hasattr(mp, 'solutions'):
        print("✅ `mediapipe.solutions` attribute found.")
    else:
        print("❌ `mediapipe.solutions` attribute NOT found.")

    # Use pip show to get more detailed information
    !pip show mediapipe

except ImportError:
    print("MediaPipe is NOT currently installed in this environment.")
    print("You might need to install it: `!pip install mediapipe`")
except Exception as e:
    print(f"An unexpected error occurred while checking MediaPipe: {e}")

print("\n--- Checking for other mediapipe-related packages ---")
!pip list | grep -i mediapipe

# 创建原始数据、处理后的地标数据、以及模型存储文件夹
!mkdir -p data/raw data/processed models/baseline

# 下载与处理好的landmark
!kaggle datasets download -d sohier/461054610546105
!unzip -q 461054610546105.zip -d data/processed/asl_rerun

# 下载wlasl视频

!kaggle datasets download -d risangbaskoro/wlasl-processed
!unzip -q wlasl-processed.zip -d data/raw/wlasl

from google.colab import drive
drive.mount('/content/drive')

# 这样文件夹会永远保存在你的 Google Drive 中
!mkdir -p /content/drive/MyDrive/Gemma4Good/data/raw
!mkdir -p /content/drive/MyDrive/Gemma4Good/data/processed
!mkdir -p /content/drive/MyDrive/Gemma4Good/models/baseline

# 下载预处理好的 Landmark刚创建的文件夹
!kaggle datasets download -d sohier/461054610546105 -p ./data/processed/asl_rerun --unzip

# 下载全身地标模型文件（包含脸、手、姿态）
!wget -O holistic_landmarker.task https://storage.googleapis.com/mediapipe-models/holistic_landmarker/holistic_landmarker/float16/latest/holistic_landmarker.task

import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision
import cv2
import pandas as pd
import numpy as np

# 1. 配置检测器
base_options = python.BaseOptions(model_asset_path='holistic_landmarker.task')
# 修改 options 配置
options = vision.HolisticLandmarkerOptions(
    base_options=base_options,
    output_face_blendshapes=False, # 关掉这个，可以提速并减少冲突
    min_face_detection_confidence=0.3,
    min_hand_landmarks_confidence=0.3,
    min_pose_landmarks_confidence=0.3
)
detector = vision.HolisticLandmarker.create_from_options(options)
detector = vision.HolisticLandmarker.create_from_options(options)

import numpy as np
import pandas as pd
import cv2

def get_landmarks_dataframe(video_path, detector):
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        print(f"❌ 错误：无法打开视频文件 {video_path}")
        return pd.DataFrame()

    all_rows = []
    frame_idx = 0

    # --- 内部定义辅助函数，防止 NameError ---
    def flatten_landmarks(landmarks, label, expected_count):
        points = []
        # 修复点：Tasks API 的 landmarks 已经是一个可迭代的列表
        if landmarks:
            # 去掉了之前的 landmarks[0]，直接遍历 landmarks
            for i, lm in enumerate(landmarks):
                points.append({
                    'frame': frame_idx,
                    'type': label,
                    'landmark_index': i,
                    'x': lm.x, 'y': lm.y, 'z': lm.z
                })
        else:
            # 占位符逻辑保持不变
            for i in range(expected_count):
                points.append({
                    'frame': frame_idx,
                    'type': label,
                    'landmark_index': i,
                    'x': np.nan, 'y': np.nan, 'z': np.nan
                })
        return points

    while cap.isOpened():
        success, frame = cap.read()
        if not success: break

        # 转换图像并识别
        mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
        detection_result = detector.detect(mp_image)

        # 定义这一帧的数据容器
        frame_data = []

        # 严格按照顺序提取 543 个点
        frame_data += flatten_landmarks(detection_result.face_landmarks, 'face', 468)
        frame_data += flatten_landmarks(detection_result.left_hand_landmarks, 'left_hand', 21)
        frame_data += flatten_landmarks(detection_result.pose_landmarks, 'pose', 33)
        frame_data += flatten_landmarks(detection_result.right_hand_landmarks, 'right_hand', 21)

        all_rows.extend(frame_data)
        frame_idx += 1

    cap.release()

    if not all_rows:
        return pd.DataFrame()

    df = pd.DataFrame(all_rows)

    # 自动进行线性插值，修复空洞
    df[['x', 'y', 'z']] = df.groupby(['type', 'landmark_index'])[['x', 'y', 'z']].transform(
        lambda x: x.interpolate(method='linear').fillna(method='ffill').fillna(method='bfill')
    )

    return df

# 运行转化
video_file = "/content/data/raw/wlasl/videos/00430.mp4" # 确保路径正确
df_result = get_landmarks_dataframe(video_file, detector)

if not df_result.empty:
    df_result.to_parquet("output.parquet")
    print(f"✅ 成功！生成了 {len(df_result)} 行数据。")
else:
    print("❌ 转化失败，请检查视频路径或 detector 设置。")

print(df_result.head())

import os
import gc
import pandas as pd
import numpy as np
import cv2
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision
from tqdm import tqdm

def batch_process_videos(video_dir, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    video_files = [f for f in os.listdir(video_dir) if f.endswith('.mp4')]
    manifest = []

    print(f"🚀 开始流水线处理，共 {len(video_files)} 个视频...")

    for video_name in tqdm(video_files):
        video_path = os.path.join(video_dir, video_name)
        video_id = video_name.split('.')[0]

        # --- 关键点：每个视频新开一个实例，或者确保旧实例被清理 ---
        # 对于批量处理，建议在循环内启动 detector 以彻底隔离状态
        detector = vision.HolisticLandmarker.create_from_options(options)

        try:
            # 调用之前的 get_landmarks_dataframe 逻辑
            df_result = get_landmarks_dataframe(video_path, detector)

            if not df_result.empty:
                # 保存为 Parquet
                save_path = os.path.join(output_dir, f"{video_id}.parquet")
                df_result.to_parquet(save_path)
                manifest.append({"video_id": video_id, "file_path": save_path})

        except Exception as e:
            print(f"❌ 视频 {video_id} 转换失败: {e}")

        finally:
            # --- 核心修复：手动关detector，别让它一直亮着耗电 ---
            detector.close()
            del detector
            gc.collect() # 强制垃圾回收

    # 生成索引表
    pd.DataFrame(manifest).to_csv("train.csv", index=False)
    print("✅ 所有任务处理完毕，train.csv 已生成。")

# 运行批量处理
video_dir = "/content/data/raw/wlasl/videos"
output_dir = "/content/data/processed/asl_parquet"
batch_process_videos(video_dir, output_dir)